#version: '3.8'
#
#services:
#  db:
#    image: postgres:12.4-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    env_file:
#      - .env.docker
#    restart: always
#    ports:
#    - "5433:5432"
#
#  frontend:
#    build: ../frontend_react/.
#    volumes:
#      - frontend:/app/build
#    depends_on:
#      - db
#
#  backend:
#    build: ../skymarket/.
#    tty: true
#    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - .:/app
#    ports:
#      - '8000:8000'
#      - '3000:3000'
#    depends_on:
#      db:
#        condition: service_healthy
#
#
#  nginx:
#    image: nginx:1.19.3
#    ports:
#      - "8000:8000"
#      - "3000:3000"
#    command: nginx -g 'daemon off;'
#    volumes:
#      - ../skymarket/django_static/:/usr/share/nginx/html/django_static/
#      - ../skymarket/django_media/:/usr/share/nginx/html/django_media/
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - frontend:/usr/share/nginx/html/
#    restart: always
#    depends_on:
#      - db
#      - frontend
#      - backend
#
#volumes:
#  postgres_data:
#  frontend: